//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class Menu
{
    public int id { get; set; }
    public int pId { get; set; }
    public string name { get; set; }
    public Nullable<bool> open { get; set; }
    public string icon { get; set; }
    public string iconOpen { get; set; }
    public string iconClose { get; set; }
    public Nullable<bool> @checked { get; set; }
    public Nullable<bool> nocheck { get; set; }
}

public partial class SysUser
{
    public string YongHu { get; set; }
    public string MiMa { get; set; }
    public Nullable<int> Level { get; set; }
}

public partial class 华青路
{
    public System.DateTime DateTime { get; set; }
    public double Val { get; set; }
    public Nullable<double> PH { get; set; }
    public Nullable<double> 前液位 { get; set; }
    public Nullable<double> 后液位 { get; set; }
    public Nullable<double> 瞬时流量 { get; set; }
}

public partial class 通波塘
{
    public System.DateTime DateTime { get; set; }
    public double Val { get; set; }
    public string Ann { get; set; }
    public Nullable<double> PH { get; set; }
    public Nullable<double> 前液位 { get; set; }
    public Nullable<double> 后液位 { get; set; }
    public Nullable<double> 瞬时流量 { get; set; }
}

public partial class 新区路
{
    public System.DateTime DateTime { get; set; }
    public double Val { get; set; }
    public string Ann { get; set; }
    public Nullable<double> PH { get; set; }
    public Nullable<double> 前液位 { get; set; }
    public Nullable<double> 后液位 { get; set; }
    public Nullable<double> 瞬时流量 { get; set; }
}

public partial class 新业路
{
    public System.DateTime DateTime { get; set; }
    public double Val { get; set; }
    public string Ann { get; set; }
    public Nullable<double> PH { get; set; }
    public Nullable<double> 前液位 { get; set; }
    public Nullable<double> 后液位 { get; set; }
    public Nullable<double> 瞬时流量 { get; set; }
}

public partial class 赵巷A
{
    public System.DateTime DateTime { get; set; }
    public double Val { get; set; }
    public string Ann { get; set; }
    public Nullable<double> PH { get; set; }
    public Nullable<double> 前液位 { get; set; }
    public Nullable<double> 后液位 { get; set; }
    public Nullable<double> 瞬时流量 { get; set; }
}

public partial class 赵巷B
{
    public System.DateTime DateTime { get; set; }
    public double Val { get; set; }
    public string Ann { get; set; }
    public Nullable<double> PH { get; set; }
    public Nullable<double> 前液位 { get; set; }
    public Nullable<double> 后液位 { get; set; }
    public Nullable<double> 瞬时流量 { get; set; }
}

public partial class 赵巷C
{
    public System.DateTime DateTime { get; set; }
    public double Val { get; set; }
    public string Ann { get; set; }
    public Nullable<double> PH { get; set; }
    public Nullable<double> 前液位 { get; set; }
    public Nullable<double> 后液位 { get; set; }
    public Nullable<double> 瞬时流量 { get; set; }
}

public partial class 赵重路
{
    public System.DateTime DateTime { get; set; }
    public double Val { get; set; }
    public string Ann { get; set; }
    public Nullable<double> PH { get; set; }
    public Nullable<double> 前液位 { get; set; }
    public Nullable<double> 后液位 { get; set; }
    public Nullable<double> 瞬时流量 { get; set; }
}
