//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class Menu
{
    public int id { get; set; }
    public int pId { get; set; }
    public string name { get; set; }
    public Nullable<bool> open { get; set; }
    public string icon { get; set; }
    public string iconOpen { get; set; }
    public string iconClose { get; set; }
    public Nullable<bool> @checked { get; set; }
    public Nullable<bool> nocheck { get; set; }
}

public partial class SysUser
{
    public string YongHu { get; set; }
    public string MiMa { get; set; }
    public Nullable<int> Level { get; set; }
}

public partial class 好氧1_NH3N
{
    public System.DateTime DateTime { get; set; }
    public double Val { get; set; }
    public string Ann { get; set; }
}

public partial class 好氧2_NH3N
{
    public System.DateTime DateTime { get; set; }
    public double Val { get; set; }
    public string Ann { get; set; }
}

public partial class 好氧3_DO
{
    public System.DateTime DateTime { get; set; }
    public double Val { get; set; }
    public string Ann { get; set; }
}

public partial class 好氧4_DO
{
    public System.DateTime DateTime { get; set; }
    public double Val { get; set; }
    public string Ann { get; set; }
}

public partial class 后缺氧1_MLSS
{
    public System.DateTime DateTime { get; set; }
    public double Val { get; set; }
    public string Ann { get; set; }
}

public partial class 后缺氧2_MLSS
{
    public System.DateTime DateTime { get; set; }
    public double Val { get; set; }
    public string Ann { get; set; }
}

public partial class 前缺氧1_DO
{
    public System.DateTime DateTime { get; set; }
    public double Val { get; set; }
    public string Ann { get; set; }
}

public partial class 前缺氧2_DO
{
    public System.DateTime DateTime { get; set; }
    public double Val { get; set; }
    public string Ann { get; set; }
}
