//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace QPCHARTModel
{
    #region 上下文
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    public partial class QPCHARTEntities : ObjectContext
    {
        #region 构造函数
    
        /// <summary>
        /// 请使用应用程序配置文件的“QPCHARTEntities”部分中的连接字符串初始化新 QPCHARTEntities 对象。
        /// </summary>
        public QPCHARTEntities() : base("name=QPCHARTEntities", "QPCHARTEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 QPCHARTEntities 对象。
        /// </summary>
        public QPCHARTEntities(string connectionString) : base(connectionString, "QPCHARTEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 QPCHARTEntities 对象。
        /// </summary>
        public QPCHARTEntities(EntityConnection connection) : base(connection, "QPCHARTEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region 分部方法
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet 属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<Menu> Menu
        {
            get
            {
                if ((_Menu == null))
                {
                    _Menu = base.CreateObjectSet<Menu>("Menu");
                }
                return _Menu;
            }
        }
        private ObjectSet<Menu> _Menu;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<SysUser> SysUser
        {
            get
            {
                if ((_SysUser == null))
                {
                    _SysUser = base.CreateObjectSet<SysUser>("SysUser");
                }
                return _SysUser;
            }
        }
        private ObjectSet<SysUser> _SysUser;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<华青路> 华青路
        {
            get
            {
                if ((_华青路 == null))
                {
                    _华青路 = base.CreateObjectSet<华青路>("华青路");
                }
                return _华青路;
            }
        }
        private ObjectSet<华青路> _华青路;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<通波塘> 通波塘
        {
            get
            {
                if ((_通波塘 == null))
                {
                    _通波塘 = base.CreateObjectSet<通波塘>("通波塘");
                }
                return _通波塘;
            }
        }
        private ObjectSet<通波塘> _通波塘;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<新区路> 新区路
        {
            get
            {
                if ((_新区路 == null))
                {
                    _新区路 = base.CreateObjectSet<新区路>("新区路");
                }
                return _新区路;
            }
        }
        private ObjectSet<新区路> _新区路;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<新业路> 新业路
        {
            get
            {
                if ((_新业路 == null))
                {
                    _新业路 = base.CreateObjectSet<新业路>("新业路");
                }
                return _新业路;
            }
        }
        private ObjectSet<新业路> _新业路;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<赵巷A> 赵巷A
        {
            get
            {
                if ((_赵巷A == null))
                {
                    _赵巷A = base.CreateObjectSet<赵巷A>("赵巷A");
                }
                return _赵巷A;
            }
        }
        private ObjectSet<赵巷A> _赵巷A;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<赵巷B> 赵巷B
        {
            get
            {
                if ((_赵巷B == null))
                {
                    _赵巷B = base.CreateObjectSet<赵巷B>("赵巷B");
                }
                return _赵巷B;
            }
        }
        private ObjectSet<赵巷B> _赵巷B;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<赵巷C> 赵巷C
        {
            get
            {
                if ((_赵巷C == null))
                {
                    _赵巷C = base.CreateObjectSet<赵巷C>("赵巷C");
                }
                return _赵巷C;
            }
        }
        private ObjectSet<赵巷C> _赵巷C;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<赵重路> 赵重路
        {
            get
            {
                if ((_赵重路 == null))
                {
                    _赵重路 = base.CreateObjectSet<赵重路>("赵重路");
                }
                return _赵重路;
            }
        }
        private ObjectSet<赵重路> _赵重路;

        #endregion

        #region AddTo 方法
    
        /// <summary>
        /// 用于向 Menu EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToMenu(Menu menu)
        {
            base.AddObject("Menu", menu);
        }
    
        /// <summary>
        /// 用于向 SysUser EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToSysUser(SysUser sysUser)
        {
            base.AddObject("SysUser", sysUser);
        }
    
        /// <summary>
        /// 用于向 华青路 EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddTo华青路(华青路 华青路)
        {
            base.AddObject("华青路", 华青路);
        }
    
        /// <summary>
        /// 用于向 通波塘 EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddTo通波塘(通波塘 通波塘)
        {
            base.AddObject("通波塘", 通波塘);
        }
    
        /// <summary>
        /// 用于向 新区路 EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddTo新区路(新区路 新区路)
        {
            base.AddObject("新区路", 新区路);
        }
    
        /// <summary>
        /// 用于向 新业路 EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddTo新业路(新业路 新业路)
        {
            base.AddObject("新业路", 新业路);
        }
    
        /// <summary>
        /// 用于向 赵巷A EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddTo赵巷A(赵巷A 赵巷A)
        {
            base.AddObject("赵巷A", 赵巷A);
        }
    
        /// <summary>
        /// 用于向 赵巷B EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddTo赵巷B(赵巷B 赵巷B)
        {
            base.AddObject("赵巷B", 赵巷B);
        }
    
        /// <summary>
        /// 用于向 赵巷C EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddTo赵巷C(赵巷C 赵巷C)
        {
            base.AddObject("赵巷C", 赵巷C);
        }
    
        /// <summary>
        /// 用于向 赵重路 EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddTo赵重路(赵重路 赵重路)
        {
            base.AddObject("赵重路", 赵重路);
        }

        #endregion

    }

    #endregion

    #region 实体
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="QPCHARTModel", Name="Menu")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Menu : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 Menu 对象。
        /// </summary>
        /// <param name="id">id 属性的初始值。</param>
        /// <param name="pId">pId 属性的初始值。</param>
        public static Menu CreateMenu(global::System.Int32 id, global::System.Int32 pId)
        {
            Menu menu = new Menu();
            menu.id = id;
            menu.pId = pId;
            return menu;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 pId
        {
            get
            {
                return _pId;
            }
            set
            {
                OnpIdChanging(value);
                ReportPropertyChanging("pId");
                _pId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("pId");
                OnpIdChanged();
            }
        }
        private global::System.Int32 _pId;
        partial void OnpIdChanging(global::System.Int32 value);
        partial void OnpIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> open
        {
            get
            {
                return _open;
            }
            set
            {
                OnopenChanging(value);
                ReportPropertyChanging("open");
                _open = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("open");
                OnopenChanged();
            }
        }
        private Nullable<global::System.Boolean> _open;
        partial void OnopenChanging(Nullable<global::System.Boolean> value);
        partial void OnopenChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String icon
        {
            get
            {
                return _icon;
            }
            set
            {
                OniconChanging(value);
                ReportPropertyChanging("icon");
                _icon = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("icon");
                OniconChanged();
            }
        }
        private global::System.String _icon;
        partial void OniconChanging(global::System.String value);
        partial void OniconChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String iconOpen
        {
            get
            {
                return _iconOpen;
            }
            set
            {
                OniconOpenChanging(value);
                ReportPropertyChanging("iconOpen");
                _iconOpen = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("iconOpen");
                OniconOpenChanged();
            }
        }
        private global::System.String _iconOpen;
        partial void OniconOpenChanging(global::System.String value);
        partial void OniconOpenChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String iconClose
        {
            get
            {
                return _iconClose;
            }
            set
            {
                OniconCloseChanging(value);
                ReportPropertyChanging("iconClose");
                _iconClose = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("iconClose");
                OniconCloseChanged();
            }
        }
        private global::System.String _iconClose;
        partial void OniconCloseChanging(global::System.String value);
        partial void OniconCloseChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> @checked
        {
            get
            {
                return _checked;
            }
            set
            {
                OncheckedChanging(value);
                ReportPropertyChanging("checked");
                _checked = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("checked");
                OncheckedChanged();
            }
        }
        private Nullable<global::System.Boolean> _checked;
        partial void OncheckedChanging(Nullable<global::System.Boolean> value);
        partial void OncheckedChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> nocheck
        {
            get
            {
                return _nocheck;
            }
            set
            {
                OnnocheckChanging(value);
                ReportPropertyChanging("nocheck");
                _nocheck = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("nocheck");
                OnnocheckChanged();
            }
        }
        private Nullable<global::System.Boolean> _nocheck;
        partial void OnnocheckChanging(Nullable<global::System.Boolean> value);
        partial void OnnocheckChanged();

        #endregion

    
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="QPCHARTModel", Name="SysUser")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class SysUser : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 SysUser 对象。
        /// </summary>
        /// <param name="yongHu">YongHu 属性的初始值。</param>
        /// <param name="miMa">MiMa 属性的初始值。</param>
        public static SysUser CreateSysUser(global::System.String yongHu, global::System.String miMa)
        {
            SysUser sysUser = new SysUser();
            sysUser.YongHu = yongHu;
            sysUser.MiMa = miMa;
            return sysUser;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String YongHu
        {
            get
            {
                return _YongHu;
            }
            set
            {
                if (_YongHu != value)
                {
                    OnYongHuChanging(value);
                    ReportPropertyChanging("YongHu");
                    _YongHu = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("YongHu");
                    OnYongHuChanged();
                }
            }
        }
        private global::System.String _YongHu;
        partial void OnYongHuChanging(global::System.String value);
        partial void OnYongHuChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String MiMa
        {
            get
            {
                return _MiMa;
            }
            set
            {
                OnMiMaChanging(value);
                ReportPropertyChanging("MiMa");
                _MiMa = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("MiMa");
                OnMiMaChanged();
            }
        }
        private global::System.String _MiMa;
        partial void OnMiMaChanging(global::System.String value);
        partial void OnMiMaChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Level
        {
            get
            {
                return _Level;
            }
            set
            {
                OnLevelChanging(value);
                ReportPropertyChanging("Level");
                _Level = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Level");
                OnLevelChanged();
            }
        }
        private Nullable<global::System.Int32> _Level;
        partial void OnLevelChanging(Nullable<global::System.Int32> value);
        partial void OnLevelChanged();

        #endregion

    
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="QPCHARTModel", Name="华青路")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class 华青路 : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 华青路 对象。
        /// </summary>
        /// <param name="dateTime">DateTime 属性的初始值。</param>
        /// <param name="val">Val 属性的初始值。</param>
        public static 华青路 Create华青路(global::System.DateTime dateTime, global::System.Double val)
        {
            华青路 华青路 = new 华青路();
            华青路.DateTime = dateTime;
            华青路.Val = val;
            return 华青路;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DateTime
        {
            get
            {
                return _DateTime;
            }
            set
            {
                if (_DateTime != value)
                {
                    OnDateTimeChanging(value);
                    ReportPropertyChanging("DateTime");
                    _DateTime = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("DateTime");
                    OnDateTimeChanged();
                }
            }
        }
        private global::System.DateTime _DateTime;
        partial void OnDateTimeChanging(global::System.DateTime value);
        partial void OnDateTimeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double Val
        {
            get
            {
                return _Val;
            }
            set
            {
                OnValChanging(value);
                ReportPropertyChanging("Val");
                _Val = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Val");
                OnValChanged();
            }
        }
        private global::System.Double _Val;
        partial void OnValChanging(global::System.Double value);
        partial void OnValChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> PH
        {
            get
            {
                return _PH;
            }
            set
            {
                OnPHChanging(value);
                ReportPropertyChanging("PH");
                _PH = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PH");
                OnPHChanged();
            }
        }
        private Nullable<global::System.Double> _PH;
        partial void OnPHChanging(Nullable<global::System.Double> value);
        partial void OnPHChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> 前液位
        {
            get
            {
                return _前液位;
            }
            set
            {
                On前液位Changing(value);
                ReportPropertyChanging("前液位");
                _前液位 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("前液位");
                On前液位Changed();
            }
        }
        private Nullable<global::System.Double> _前液位;
        partial void On前液位Changing(Nullable<global::System.Double> value);
        partial void On前液位Changed();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> 后液位
        {
            get
            {
                return _后液位;
            }
            set
            {
                On后液位Changing(value);
                ReportPropertyChanging("后液位");
                _后液位 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("后液位");
                On后液位Changed();
            }
        }
        private Nullable<global::System.Double> _后液位;
        partial void On后液位Changing(Nullable<global::System.Double> value);
        partial void On后液位Changed();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> 瞬时流量
        {
            get
            {
                return _瞬时流量;
            }
            set
            {
                On瞬时流量Changing(value);
                ReportPropertyChanging("瞬时流量");
                _瞬时流量 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("瞬时流量");
                On瞬时流量Changed();
            }
        }
        private Nullable<global::System.Double> _瞬时流量;
        partial void On瞬时流量Changing(Nullable<global::System.Double> value);
        partial void On瞬时流量Changed();

        #endregion

    
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="QPCHARTModel", Name="通波塘")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class 通波塘 : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 通波塘 对象。
        /// </summary>
        /// <param name="dateTime">DateTime 属性的初始值。</param>
        /// <param name="val">Val 属性的初始值。</param>
        public static 通波塘 Create通波塘(global::System.DateTime dateTime, global::System.Double val)
        {
            通波塘 通波塘 = new 通波塘();
            通波塘.DateTime = dateTime;
            通波塘.Val = val;
            return 通波塘;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DateTime
        {
            get
            {
                return _DateTime;
            }
            set
            {
                if (_DateTime != value)
                {
                    OnDateTimeChanging(value);
                    ReportPropertyChanging("DateTime");
                    _DateTime = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("DateTime");
                    OnDateTimeChanged();
                }
            }
        }
        private global::System.DateTime _DateTime;
        partial void OnDateTimeChanging(global::System.DateTime value);
        partial void OnDateTimeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double Val
        {
            get
            {
                return _Val;
            }
            set
            {
                OnValChanging(value);
                ReportPropertyChanging("Val");
                _Val = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Val");
                OnValChanged();
            }
        }
        private global::System.Double _Val;
        partial void OnValChanging(global::System.Double value);
        partial void OnValChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Ann
        {
            get
            {
                return _Ann;
            }
            set
            {
                OnAnnChanging(value);
                ReportPropertyChanging("Ann");
                _Ann = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Ann");
                OnAnnChanged();
            }
        }
        private global::System.String _Ann;
        partial void OnAnnChanging(global::System.String value);
        partial void OnAnnChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> PH
        {
            get
            {
                return _PH;
            }
            set
            {
                OnPHChanging(value);
                ReportPropertyChanging("PH");
                _PH = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PH");
                OnPHChanged();
            }
        }
        private Nullable<global::System.Double> _PH;
        partial void OnPHChanging(Nullable<global::System.Double> value);
        partial void OnPHChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> 前液位
        {
            get
            {
                return _前液位;
            }
            set
            {
                On前液位Changing(value);
                ReportPropertyChanging("前液位");
                _前液位 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("前液位");
                On前液位Changed();
            }
        }
        private Nullable<global::System.Double> _前液位;
        partial void On前液位Changing(Nullable<global::System.Double> value);
        partial void On前液位Changed();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> 后液位
        {
            get
            {
                return _后液位;
            }
            set
            {
                On后液位Changing(value);
                ReportPropertyChanging("后液位");
                _后液位 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("后液位");
                On后液位Changed();
            }
        }
        private Nullable<global::System.Double> _后液位;
        partial void On后液位Changing(Nullable<global::System.Double> value);
        partial void On后液位Changed();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> 瞬时流量
        {
            get
            {
                return _瞬时流量;
            }
            set
            {
                On瞬时流量Changing(value);
                ReportPropertyChanging("瞬时流量");
                _瞬时流量 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("瞬时流量");
                On瞬时流量Changed();
            }
        }
        private Nullable<global::System.Double> _瞬时流量;
        partial void On瞬时流量Changing(Nullable<global::System.Double> value);
        partial void On瞬时流量Changed();

        #endregion

    
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="QPCHARTModel", Name="新区路")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class 新区路 : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 新区路 对象。
        /// </summary>
        /// <param name="dateTime">DateTime 属性的初始值。</param>
        /// <param name="val">Val 属性的初始值。</param>
        public static 新区路 Create新区路(global::System.DateTime dateTime, global::System.Double val)
        {
            新区路 新区路 = new 新区路();
            新区路.DateTime = dateTime;
            新区路.Val = val;
            return 新区路;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DateTime
        {
            get
            {
                return _DateTime;
            }
            set
            {
                if (_DateTime != value)
                {
                    OnDateTimeChanging(value);
                    ReportPropertyChanging("DateTime");
                    _DateTime = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("DateTime");
                    OnDateTimeChanged();
                }
            }
        }
        private global::System.DateTime _DateTime;
        partial void OnDateTimeChanging(global::System.DateTime value);
        partial void OnDateTimeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double Val
        {
            get
            {
                return _Val;
            }
            set
            {
                OnValChanging(value);
                ReportPropertyChanging("Val");
                _Val = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Val");
                OnValChanged();
            }
        }
        private global::System.Double _Val;
        partial void OnValChanging(global::System.Double value);
        partial void OnValChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Ann
        {
            get
            {
                return _Ann;
            }
            set
            {
                OnAnnChanging(value);
                ReportPropertyChanging("Ann");
                _Ann = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Ann");
                OnAnnChanged();
            }
        }
        private global::System.String _Ann;
        partial void OnAnnChanging(global::System.String value);
        partial void OnAnnChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> PH
        {
            get
            {
                return _PH;
            }
            set
            {
                OnPHChanging(value);
                ReportPropertyChanging("PH");
                _PH = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PH");
                OnPHChanged();
            }
        }
        private Nullable<global::System.Double> _PH;
        partial void OnPHChanging(Nullable<global::System.Double> value);
        partial void OnPHChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> 前液位
        {
            get
            {
                return _前液位;
            }
            set
            {
                On前液位Changing(value);
                ReportPropertyChanging("前液位");
                _前液位 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("前液位");
                On前液位Changed();
            }
        }
        private Nullable<global::System.Double> _前液位;
        partial void On前液位Changing(Nullable<global::System.Double> value);
        partial void On前液位Changed();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> 后液位
        {
            get
            {
                return _后液位;
            }
            set
            {
                On后液位Changing(value);
                ReportPropertyChanging("后液位");
                _后液位 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("后液位");
                On后液位Changed();
            }
        }
        private Nullable<global::System.Double> _后液位;
        partial void On后液位Changing(Nullable<global::System.Double> value);
        partial void On后液位Changed();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> 瞬时流量
        {
            get
            {
                return _瞬时流量;
            }
            set
            {
                On瞬时流量Changing(value);
                ReportPropertyChanging("瞬时流量");
                _瞬时流量 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("瞬时流量");
                On瞬时流量Changed();
            }
        }
        private Nullable<global::System.Double> _瞬时流量;
        partial void On瞬时流量Changing(Nullable<global::System.Double> value);
        partial void On瞬时流量Changed();

        #endregion

    
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="QPCHARTModel", Name="新业路")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class 新业路 : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 新业路 对象。
        /// </summary>
        /// <param name="dateTime">DateTime 属性的初始值。</param>
        /// <param name="val">Val 属性的初始值。</param>
        public static 新业路 Create新业路(global::System.DateTime dateTime, global::System.Double val)
        {
            新业路 新业路 = new 新业路();
            新业路.DateTime = dateTime;
            新业路.Val = val;
            return 新业路;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DateTime
        {
            get
            {
                return _DateTime;
            }
            set
            {
                if (_DateTime != value)
                {
                    OnDateTimeChanging(value);
                    ReportPropertyChanging("DateTime");
                    _DateTime = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("DateTime");
                    OnDateTimeChanged();
                }
            }
        }
        private global::System.DateTime _DateTime;
        partial void OnDateTimeChanging(global::System.DateTime value);
        partial void OnDateTimeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double Val
        {
            get
            {
                return _Val;
            }
            set
            {
                OnValChanging(value);
                ReportPropertyChanging("Val");
                _Val = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Val");
                OnValChanged();
            }
        }
        private global::System.Double _Val;
        partial void OnValChanging(global::System.Double value);
        partial void OnValChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Ann
        {
            get
            {
                return _Ann;
            }
            set
            {
                OnAnnChanging(value);
                ReportPropertyChanging("Ann");
                _Ann = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Ann");
                OnAnnChanged();
            }
        }
        private global::System.String _Ann;
        partial void OnAnnChanging(global::System.String value);
        partial void OnAnnChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> PH
        {
            get
            {
                return _PH;
            }
            set
            {
                OnPHChanging(value);
                ReportPropertyChanging("PH");
                _PH = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PH");
                OnPHChanged();
            }
        }
        private Nullable<global::System.Double> _PH;
        partial void OnPHChanging(Nullable<global::System.Double> value);
        partial void OnPHChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> 前液位
        {
            get
            {
                return _前液位;
            }
            set
            {
                On前液位Changing(value);
                ReportPropertyChanging("前液位");
                _前液位 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("前液位");
                On前液位Changed();
            }
        }
        private Nullable<global::System.Double> _前液位;
        partial void On前液位Changing(Nullable<global::System.Double> value);
        partial void On前液位Changed();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> 后液位
        {
            get
            {
                return _后液位;
            }
            set
            {
                On后液位Changing(value);
                ReportPropertyChanging("后液位");
                _后液位 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("后液位");
                On后液位Changed();
            }
        }
        private Nullable<global::System.Double> _后液位;
        partial void On后液位Changing(Nullable<global::System.Double> value);
        partial void On后液位Changed();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> 瞬时流量
        {
            get
            {
                return _瞬时流量;
            }
            set
            {
                On瞬时流量Changing(value);
                ReportPropertyChanging("瞬时流量");
                _瞬时流量 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("瞬时流量");
                On瞬时流量Changed();
            }
        }
        private Nullable<global::System.Double> _瞬时流量;
        partial void On瞬时流量Changing(Nullable<global::System.Double> value);
        partial void On瞬时流量Changed();

        #endregion

    
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="QPCHARTModel", Name="赵巷A")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class 赵巷A : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 赵巷A 对象。
        /// </summary>
        /// <param name="dateTime">DateTime 属性的初始值。</param>
        /// <param name="val">Val 属性的初始值。</param>
        public static 赵巷A Create赵巷A(global::System.DateTime dateTime, global::System.Double val)
        {
            赵巷A 赵巷A = new 赵巷A();
            赵巷A.DateTime = dateTime;
            赵巷A.Val = val;
            return 赵巷A;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DateTime
        {
            get
            {
                return _DateTime;
            }
            set
            {
                if (_DateTime != value)
                {
                    OnDateTimeChanging(value);
                    ReportPropertyChanging("DateTime");
                    _DateTime = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("DateTime");
                    OnDateTimeChanged();
                }
            }
        }
        private global::System.DateTime _DateTime;
        partial void OnDateTimeChanging(global::System.DateTime value);
        partial void OnDateTimeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double Val
        {
            get
            {
                return _Val;
            }
            set
            {
                OnValChanging(value);
                ReportPropertyChanging("Val");
                _Val = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Val");
                OnValChanged();
            }
        }
        private global::System.Double _Val;
        partial void OnValChanging(global::System.Double value);
        partial void OnValChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Ann
        {
            get
            {
                return _Ann;
            }
            set
            {
                OnAnnChanging(value);
                ReportPropertyChanging("Ann");
                _Ann = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Ann");
                OnAnnChanged();
            }
        }
        private global::System.String _Ann;
        partial void OnAnnChanging(global::System.String value);
        partial void OnAnnChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> PH
        {
            get
            {
                return _PH;
            }
            set
            {
                OnPHChanging(value);
                ReportPropertyChanging("PH");
                _PH = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PH");
                OnPHChanged();
            }
        }
        private Nullable<global::System.Double> _PH;
        partial void OnPHChanging(Nullable<global::System.Double> value);
        partial void OnPHChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> 前液位
        {
            get
            {
                return _前液位;
            }
            set
            {
                On前液位Changing(value);
                ReportPropertyChanging("前液位");
                _前液位 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("前液位");
                On前液位Changed();
            }
        }
        private Nullable<global::System.Double> _前液位;
        partial void On前液位Changing(Nullable<global::System.Double> value);
        partial void On前液位Changed();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> 后液位
        {
            get
            {
                return _后液位;
            }
            set
            {
                On后液位Changing(value);
                ReportPropertyChanging("后液位");
                _后液位 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("后液位");
                On后液位Changed();
            }
        }
        private Nullable<global::System.Double> _后液位;
        partial void On后液位Changing(Nullable<global::System.Double> value);
        partial void On后液位Changed();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> 瞬时流量
        {
            get
            {
                return _瞬时流量;
            }
            set
            {
                On瞬时流量Changing(value);
                ReportPropertyChanging("瞬时流量");
                _瞬时流量 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("瞬时流量");
                On瞬时流量Changed();
            }
        }
        private Nullable<global::System.Double> _瞬时流量;
        partial void On瞬时流量Changing(Nullable<global::System.Double> value);
        partial void On瞬时流量Changed();

        #endregion

    
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="QPCHARTModel", Name="赵巷B")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class 赵巷B : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 赵巷B 对象。
        /// </summary>
        /// <param name="dateTime">DateTime 属性的初始值。</param>
        /// <param name="val">Val 属性的初始值。</param>
        public static 赵巷B Create赵巷B(global::System.DateTime dateTime, global::System.Double val)
        {
            赵巷B 赵巷B = new 赵巷B();
            赵巷B.DateTime = dateTime;
            赵巷B.Val = val;
            return 赵巷B;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DateTime
        {
            get
            {
                return _DateTime;
            }
            set
            {
                if (_DateTime != value)
                {
                    OnDateTimeChanging(value);
                    ReportPropertyChanging("DateTime");
                    _DateTime = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("DateTime");
                    OnDateTimeChanged();
                }
            }
        }
        private global::System.DateTime _DateTime;
        partial void OnDateTimeChanging(global::System.DateTime value);
        partial void OnDateTimeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double Val
        {
            get
            {
                return _Val;
            }
            set
            {
                OnValChanging(value);
                ReportPropertyChanging("Val");
                _Val = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Val");
                OnValChanged();
            }
        }
        private global::System.Double _Val;
        partial void OnValChanging(global::System.Double value);
        partial void OnValChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Ann
        {
            get
            {
                return _Ann;
            }
            set
            {
                OnAnnChanging(value);
                ReportPropertyChanging("Ann");
                _Ann = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Ann");
                OnAnnChanged();
            }
        }
        private global::System.String _Ann;
        partial void OnAnnChanging(global::System.String value);
        partial void OnAnnChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> PH
        {
            get
            {
                return _PH;
            }
            set
            {
                OnPHChanging(value);
                ReportPropertyChanging("PH");
                _PH = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PH");
                OnPHChanged();
            }
        }
        private Nullable<global::System.Double> _PH;
        partial void OnPHChanging(Nullable<global::System.Double> value);
        partial void OnPHChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> 前液位
        {
            get
            {
                return _前液位;
            }
            set
            {
                On前液位Changing(value);
                ReportPropertyChanging("前液位");
                _前液位 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("前液位");
                On前液位Changed();
            }
        }
        private Nullable<global::System.Double> _前液位;
        partial void On前液位Changing(Nullable<global::System.Double> value);
        partial void On前液位Changed();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> 后液位
        {
            get
            {
                return _后液位;
            }
            set
            {
                On后液位Changing(value);
                ReportPropertyChanging("后液位");
                _后液位 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("后液位");
                On后液位Changed();
            }
        }
        private Nullable<global::System.Double> _后液位;
        partial void On后液位Changing(Nullable<global::System.Double> value);
        partial void On后液位Changed();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> 瞬时流量
        {
            get
            {
                return _瞬时流量;
            }
            set
            {
                On瞬时流量Changing(value);
                ReportPropertyChanging("瞬时流量");
                _瞬时流量 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("瞬时流量");
                On瞬时流量Changed();
            }
        }
        private Nullable<global::System.Double> _瞬时流量;
        partial void On瞬时流量Changing(Nullable<global::System.Double> value);
        partial void On瞬时流量Changed();

        #endregion

    
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="QPCHARTModel", Name="赵巷C")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class 赵巷C : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 赵巷C 对象。
        /// </summary>
        /// <param name="dateTime">DateTime 属性的初始值。</param>
        /// <param name="val">Val 属性的初始值。</param>
        public static 赵巷C Create赵巷C(global::System.DateTime dateTime, global::System.Double val)
        {
            赵巷C 赵巷C = new 赵巷C();
            赵巷C.DateTime = dateTime;
            赵巷C.Val = val;
            return 赵巷C;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DateTime
        {
            get
            {
                return _DateTime;
            }
            set
            {
                if (_DateTime != value)
                {
                    OnDateTimeChanging(value);
                    ReportPropertyChanging("DateTime");
                    _DateTime = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("DateTime");
                    OnDateTimeChanged();
                }
            }
        }
        private global::System.DateTime _DateTime;
        partial void OnDateTimeChanging(global::System.DateTime value);
        partial void OnDateTimeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double Val
        {
            get
            {
                return _Val;
            }
            set
            {
                OnValChanging(value);
                ReportPropertyChanging("Val");
                _Val = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Val");
                OnValChanged();
            }
        }
        private global::System.Double _Val;
        partial void OnValChanging(global::System.Double value);
        partial void OnValChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Ann
        {
            get
            {
                return _Ann;
            }
            set
            {
                OnAnnChanging(value);
                ReportPropertyChanging("Ann");
                _Ann = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Ann");
                OnAnnChanged();
            }
        }
        private global::System.String _Ann;
        partial void OnAnnChanging(global::System.String value);
        partial void OnAnnChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> PH
        {
            get
            {
                return _PH;
            }
            set
            {
                OnPHChanging(value);
                ReportPropertyChanging("PH");
                _PH = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PH");
                OnPHChanged();
            }
        }
        private Nullable<global::System.Double> _PH;
        partial void OnPHChanging(Nullable<global::System.Double> value);
        partial void OnPHChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> 前液位
        {
            get
            {
                return _前液位;
            }
            set
            {
                On前液位Changing(value);
                ReportPropertyChanging("前液位");
                _前液位 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("前液位");
                On前液位Changed();
            }
        }
        private Nullable<global::System.Double> _前液位;
        partial void On前液位Changing(Nullable<global::System.Double> value);
        partial void On前液位Changed();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> 后液位
        {
            get
            {
                return _后液位;
            }
            set
            {
                On后液位Changing(value);
                ReportPropertyChanging("后液位");
                _后液位 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("后液位");
                On后液位Changed();
            }
        }
        private Nullable<global::System.Double> _后液位;
        partial void On后液位Changing(Nullable<global::System.Double> value);
        partial void On后液位Changed();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> 瞬时流量
        {
            get
            {
                return _瞬时流量;
            }
            set
            {
                On瞬时流量Changing(value);
                ReportPropertyChanging("瞬时流量");
                _瞬时流量 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("瞬时流量");
                On瞬时流量Changed();
            }
        }
        private Nullable<global::System.Double> _瞬时流量;
        partial void On瞬时流量Changing(Nullable<global::System.Double> value);
        partial void On瞬时流量Changed();

        #endregion

    
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="QPCHARTModel", Name="赵重路")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class 赵重路 : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 赵重路 对象。
        /// </summary>
        /// <param name="dateTime">DateTime 属性的初始值。</param>
        /// <param name="val">Val 属性的初始值。</param>
        public static 赵重路 Create赵重路(global::System.DateTime dateTime, global::System.Double val)
        {
            赵重路 赵重路 = new 赵重路();
            赵重路.DateTime = dateTime;
            赵重路.Val = val;
            return 赵重路;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DateTime
        {
            get
            {
                return _DateTime;
            }
            set
            {
                if (_DateTime != value)
                {
                    OnDateTimeChanging(value);
                    ReportPropertyChanging("DateTime");
                    _DateTime = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("DateTime");
                    OnDateTimeChanged();
                }
            }
        }
        private global::System.DateTime _DateTime;
        partial void OnDateTimeChanging(global::System.DateTime value);
        partial void OnDateTimeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double Val
        {
            get
            {
                return _Val;
            }
            set
            {
                OnValChanging(value);
                ReportPropertyChanging("Val");
                _Val = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Val");
                OnValChanged();
            }
        }
        private global::System.Double _Val;
        partial void OnValChanging(global::System.Double value);
        partial void OnValChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Ann
        {
            get
            {
                return _Ann;
            }
            set
            {
                OnAnnChanging(value);
                ReportPropertyChanging("Ann");
                _Ann = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Ann");
                OnAnnChanged();
            }
        }
        private global::System.String _Ann;
        partial void OnAnnChanging(global::System.String value);
        partial void OnAnnChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> PH
        {
            get
            {
                return _PH;
            }
            set
            {
                OnPHChanging(value);
                ReportPropertyChanging("PH");
                _PH = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PH");
                OnPHChanged();
            }
        }
        private Nullable<global::System.Double> _PH;
        partial void OnPHChanging(Nullable<global::System.Double> value);
        partial void OnPHChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> 前液位
        {
            get
            {
                return _前液位;
            }
            set
            {
                On前液位Changing(value);
                ReportPropertyChanging("前液位");
                _前液位 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("前液位");
                On前液位Changed();
            }
        }
        private Nullable<global::System.Double> _前液位;
        partial void On前液位Changing(Nullable<global::System.Double> value);
        partial void On前液位Changed();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> 后液位
        {
            get
            {
                return _后液位;
            }
            set
            {
                On后液位Changing(value);
                ReportPropertyChanging("后液位");
                _后液位 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("后液位");
                On后液位Changed();
            }
        }
        private Nullable<global::System.Double> _后液位;
        partial void On后液位Changing(Nullable<global::System.Double> value);
        partial void On后液位Changed();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> 瞬时流量
        {
            get
            {
                return _瞬时流量;
            }
            set
            {
                On瞬时流量Changing(value);
                ReportPropertyChanging("瞬时流量");
                _瞬时流量 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("瞬时流量");
                On瞬时流量Changed();
            }
        }
        private Nullable<global::System.Double> _瞬时流量;
        partial void On瞬时流量Changing(Nullable<global::System.Double> value);
        partial void On瞬时流量Changed();

        #endregion

    
    }

    #endregion

    
}
