//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace QPCHARTModel
{
    #region 上下文
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    public partial class QPCHARTEntities : ObjectContext
    {
        #region 构造函数
    
        /// <summary>
        /// 请使用应用程序配置文件的“QPCHARTEntities”部分中的连接字符串初始化新 QPCHARTEntities 对象。
        /// </summary>
        public QPCHARTEntities() : base("name=QPCHARTEntities", "QPCHARTEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 QPCHARTEntities 对象。
        /// </summary>
        public QPCHARTEntities(string connectionString) : base(connectionString, "QPCHARTEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 QPCHARTEntities 对象。
        /// </summary>
        public QPCHARTEntities(EntityConnection connection) : base(connection, "QPCHARTEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region 分部方法
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet 属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<Menu> Menu
        {
            get
            {
                if ((_Menu == null))
                {
                    _Menu = base.CreateObjectSet<Menu>("Menu");
                }
                return _Menu;
            }
        }
        private ObjectSet<Menu> _Menu;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<SysUser> SysUser
        {
            get
            {
                if ((_SysUser == null))
                {
                    _SysUser = base.CreateObjectSet<SysUser>("SysUser");
                }
                return _SysUser;
            }
        }
        private ObjectSet<SysUser> _SysUser;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<好氧1_NH3N> 好氧1_NH3N
        {
            get
            {
                if ((_好氧1_NH3N == null))
                {
                    _好氧1_NH3N = base.CreateObjectSet<好氧1_NH3N>("好氧1_NH3N");
                }
                return _好氧1_NH3N;
            }
        }
        private ObjectSet<好氧1_NH3N> _好氧1_NH3N;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<好氧2_NH3N> 好氧2_NH3N
        {
            get
            {
                if ((_好氧2_NH3N == null))
                {
                    _好氧2_NH3N = base.CreateObjectSet<好氧2_NH3N>("好氧2_NH3N");
                }
                return _好氧2_NH3N;
            }
        }
        private ObjectSet<好氧2_NH3N> _好氧2_NH3N;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<好氧3_DO> 好氧3_DO
        {
            get
            {
                if ((_好氧3_DO == null))
                {
                    _好氧3_DO = base.CreateObjectSet<好氧3_DO>("好氧3_DO");
                }
                return _好氧3_DO;
            }
        }
        private ObjectSet<好氧3_DO> _好氧3_DO;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<好氧4_DO> 好氧4_DO
        {
            get
            {
                if ((_好氧4_DO == null))
                {
                    _好氧4_DO = base.CreateObjectSet<好氧4_DO>("好氧4_DO");
                }
                return _好氧4_DO;
            }
        }
        private ObjectSet<好氧4_DO> _好氧4_DO;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<后缺氧1_MLSS> 后缺氧1_MLSS
        {
            get
            {
                if ((_后缺氧1_MLSS == null))
                {
                    _后缺氧1_MLSS = base.CreateObjectSet<后缺氧1_MLSS>("后缺氧1_MLSS");
                }
                return _后缺氧1_MLSS;
            }
        }
        private ObjectSet<后缺氧1_MLSS> _后缺氧1_MLSS;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<后缺氧2_MLSS> 后缺氧2_MLSS
        {
            get
            {
                if ((_后缺氧2_MLSS == null))
                {
                    _后缺氧2_MLSS = base.CreateObjectSet<后缺氧2_MLSS>("后缺氧2_MLSS");
                }
                return _后缺氧2_MLSS;
            }
        }
        private ObjectSet<后缺氧2_MLSS> _后缺氧2_MLSS;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<前缺氧1_DO> 前缺氧1_DO
        {
            get
            {
                if ((_前缺氧1_DO == null))
                {
                    _前缺氧1_DO = base.CreateObjectSet<前缺氧1_DO>("前缺氧1_DO");
                }
                return _前缺氧1_DO;
            }
        }
        private ObjectSet<前缺氧1_DO> _前缺氧1_DO;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<前缺氧2_DO> 前缺氧2_DO
        {
            get
            {
                if ((_前缺氧2_DO == null))
                {
                    _前缺氧2_DO = base.CreateObjectSet<前缺氧2_DO>("前缺氧2_DO");
                }
                return _前缺氧2_DO;
            }
        }
        private ObjectSet<前缺氧2_DO> _前缺氧2_DO;

        #endregion

        #region AddTo 方法
    
        /// <summary>
        /// 用于向 Menu EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToMenu(Menu menu)
        {
            base.AddObject("Menu", menu);
        }
    
        /// <summary>
        /// 用于向 SysUser EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToSysUser(SysUser sysUser)
        {
            base.AddObject("SysUser", sysUser);
        }
    
        /// <summary>
        /// 用于向 好氧1_NH3N EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddTo好氧1_NH3N(好氧1_NH3N 好氧1_NH3N)
        {
            base.AddObject("好氧1_NH3N", 好氧1_NH3N);
        }
    
        /// <summary>
        /// 用于向 好氧2_NH3N EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddTo好氧2_NH3N(好氧2_NH3N 好氧2_NH3N)
        {
            base.AddObject("好氧2_NH3N", 好氧2_NH3N);
        }
    
        /// <summary>
        /// 用于向 好氧3_DO EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddTo好氧3_DO(好氧3_DO 好氧3_DO)
        {
            base.AddObject("好氧3_DO", 好氧3_DO);
        }
    
        /// <summary>
        /// 用于向 好氧4_DO EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddTo好氧4_DO(好氧4_DO 好氧4_DO)
        {
            base.AddObject("好氧4_DO", 好氧4_DO);
        }
    
        /// <summary>
        /// 用于向 后缺氧1_MLSS EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddTo后缺氧1_MLSS(后缺氧1_MLSS 后缺氧1_MLSS)
        {
            base.AddObject("后缺氧1_MLSS", 后缺氧1_MLSS);
        }
    
        /// <summary>
        /// 用于向 后缺氧2_MLSS EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddTo后缺氧2_MLSS(后缺氧2_MLSS 后缺氧2_MLSS)
        {
            base.AddObject("后缺氧2_MLSS", 后缺氧2_MLSS);
        }
    
        /// <summary>
        /// 用于向 前缺氧1_DO EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddTo前缺氧1_DO(前缺氧1_DO 前缺氧1_DO)
        {
            base.AddObject("前缺氧1_DO", 前缺氧1_DO);
        }
    
        /// <summary>
        /// 用于向 前缺氧2_DO EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddTo前缺氧2_DO(前缺氧2_DO 前缺氧2_DO)
        {
            base.AddObject("前缺氧2_DO", 前缺氧2_DO);
        }

        #endregion

    }

    #endregion

    #region 实体
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="QPCHARTModel", Name="Menu")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Menu : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 Menu 对象。
        /// </summary>
        /// <param name="id">id 属性的初始值。</param>
        /// <param name="pId">pId 属性的初始值。</param>
        public static Menu CreateMenu(global::System.Int32 id, global::System.Int32 pId)
        {
            Menu menu = new Menu();
            menu.id = id;
            menu.pId = pId;
            return menu;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 pId
        {
            get
            {
                return _pId;
            }
            set
            {
                OnpIdChanging(value);
                ReportPropertyChanging("pId");
                _pId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("pId");
                OnpIdChanged();
            }
        }
        private global::System.Int32 _pId;
        partial void OnpIdChanging(global::System.Int32 value);
        partial void OnpIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> open
        {
            get
            {
                return _open;
            }
            set
            {
                OnopenChanging(value);
                ReportPropertyChanging("open");
                _open = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("open");
                OnopenChanged();
            }
        }
        private Nullable<global::System.Boolean> _open;
        partial void OnopenChanging(Nullable<global::System.Boolean> value);
        partial void OnopenChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String icon
        {
            get
            {
                return _icon;
            }
            set
            {
                OniconChanging(value);
                ReportPropertyChanging("icon");
                _icon = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("icon");
                OniconChanged();
            }
        }
        private global::System.String _icon;
        partial void OniconChanging(global::System.String value);
        partial void OniconChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String iconOpen
        {
            get
            {
                return _iconOpen;
            }
            set
            {
                OniconOpenChanging(value);
                ReportPropertyChanging("iconOpen");
                _iconOpen = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("iconOpen");
                OniconOpenChanged();
            }
        }
        private global::System.String _iconOpen;
        partial void OniconOpenChanging(global::System.String value);
        partial void OniconOpenChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String iconClose
        {
            get
            {
                return _iconClose;
            }
            set
            {
                OniconCloseChanging(value);
                ReportPropertyChanging("iconClose");
                _iconClose = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("iconClose");
                OniconCloseChanged();
            }
        }
        private global::System.String _iconClose;
        partial void OniconCloseChanging(global::System.String value);
        partial void OniconCloseChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> @checked
        {
            get
            {
                return _checked;
            }
            set
            {
                OncheckedChanging(value);
                ReportPropertyChanging("checked");
                _checked = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("checked");
                OncheckedChanged();
            }
        }
        private Nullable<global::System.Boolean> _checked;
        partial void OncheckedChanging(Nullable<global::System.Boolean> value);
        partial void OncheckedChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> nocheck
        {
            get
            {
                return _nocheck;
            }
            set
            {
                OnnocheckChanging(value);
                ReportPropertyChanging("nocheck");
                _nocheck = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("nocheck");
                OnnocheckChanged();
            }
        }
        private Nullable<global::System.Boolean> _nocheck;
        partial void OnnocheckChanging(Nullable<global::System.Boolean> value);
        partial void OnnocheckChanged();

        #endregion

    
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="QPCHARTModel", Name="SysUser")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class SysUser : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 SysUser 对象。
        /// </summary>
        /// <param name="yongHu">YongHu 属性的初始值。</param>
        /// <param name="miMa">MiMa 属性的初始值。</param>
        public static SysUser CreateSysUser(global::System.String yongHu, global::System.String miMa)
        {
            SysUser sysUser = new SysUser();
            sysUser.YongHu = yongHu;
            sysUser.MiMa = miMa;
            return sysUser;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String YongHu
        {
            get
            {
                return _YongHu;
            }
            set
            {
                if (_YongHu != value)
                {
                    OnYongHuChanging(value);
                    ReportPropertyChanging("YongHu");
                    _YongHu = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("YongHu");
                    OnYongHuChanged();
                }
            }
        }
        private global::System.String _YongHu;
        partial void OnYongHuChanging(global::System.String value);
        partial void OnYongHuChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String MiMa
        {
            get
            {
                return _MiMa;
            }
            set
            {
                OnMiMaChanging(value);
                ReportPropertyChanging("MiMa");
                _MiMa = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("MiMa");
                OnMiMaChanged();
            }
        }
        private global::System.String _MiMa;
        partial void OnMiMaChanging(global::System.String value);
        partial void OnMiMaChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Level
        {
            get
            {
                return _Level;
            }
            set
            {
                OnLevelChanging(value);
                ReportPropertyChanging("Level");
                _Level = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Level");
                OnLevelChanged();
            }
        }
        private Nullable<global::System.Int32> _Level;
        partial void OnLevelChanging(Nullable<global::System.Int32> value);
        partial void OnLevelChanged();

        #endregion

    
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="QPCHARTModel", Name="好氧1_NH3N")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class 好氧1_NH3N : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 好氧1_NH3N 对象。
        /// </summary>
        /// <param name="dateTime">DateTime 属性的初始值。</param>
        /// <param name="val">Val 属性的初始值。</param>
        public static 好氧1_NH3N Create好氧1_NH3N(global::System.DateTime dateTime, global::System.Double val)
        {
            好氧1_NH3N 好氧1_NH3N = new 好氧1_NH3N();
            好氧1_NH3N.DateTime = dateTime;
            好氧1_NH3N.Val = val;
            return 好氧1_NH3N;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DateTime
        {
            get
            {
                return _DateTime;
            }
            set
            {
                if (_DateTime != value)
                {
                    OnDateTimeChanging(value);
                    ReportPropertyChanging("DateTime");
                    _DateTime = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("DateTime");
                    OnDateTimeChanged();
                }
            }
        }
        private global::System.DateTime _DateTime;
        partial void OnDateTimeChanging(global::System.DateTime value);
        partial void OnDateTimeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double Val
        {
            get
            {
                return _Val;
            }
            set
            {
                OnValChanging(value);
                ReportPropertyChanging("Val");
                _Val = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Val");
                OnValChanged();
            }
        }
        private global::System.Double _Val;
        partial void OnValChanging(global::System.Double value);
        partial void OnValChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Ann
        {
            get
            {
                return _Ann;
            }
            set
            {
                OnAnnChanging(value);
                ReportPropertyChanging("Ann");
                _Ann = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Ann");
                OnAnnChanged();
            }
        }
        private global::System.String _Ann;
        partial void OnAnnChanging(global::System.String value);
        partial void OnAnnChanged();

        #endregion

    
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="QPCHARTModel", Name="好氧2_NH3N")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class 好氧2_NH3N : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 好氧2_NH3N 对象。
        /// </summary>
        /// <param name="dateTime">DateTime 属性的初始值。</param>
        /// <param name="val">Val 属性的初始值。</param>
        public static 好氧2_NH3N Create好氧2_NH3N(global::System.DateTime dateTime, global::System.Double val)
        {
            好氧2_NH3N 好氧2_NH3N = new 好氧2_NH3N();
            好氧2_NH3N.DateTime = dateTime;
            好氧2_NH3N.Val = val;
            return 好氧2_NH3N;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DateTime
        {
            get
            {
                return _DateTime;
            }
            set
            {
                if (_DateTime != value)
                {
                    OnDateTimeChanging(value);
                    ReportPropertyChanging("DateTime");
                    _DateTime = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("DateTime");
                    OnDateTimeChanged();
                }
            }
        }
        private global::System.DateTime _DateTime;
        partial void OnDateTimeChanging(global::System.DateTime value);
        partial void OnDateTimeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double Val
        {
            get
            {
                return _Val;
            }
            set
            {
                OnValChanging(value);
                ReportPropertyChanging("Val");
                _Val = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Val");
                OnValChanged();
            }
        }
        private global::System.Double _Val;
        partial void OnValChanging(global::System.Double value);
        partial void OnValChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Ann
        {
            get
            {
                return _Ann;
            }
            set
            {
                OnAnnChanging(value);
                ReportPropertyChanging("Ann");
                _Ann = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Ann");
                OnAnnChanged();
            }
        }
        private global::System.String _Ann;
        partial void OnAnnChanging(global::System.String value);
        partial void OnAnnChanged();

        #endregion

    
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="QPCHARTModel", Name="好氧3_DO")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class 好氧3_DO : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 好氧3_DO 对象。
        /// </summary>
        /// <param name="dateTime">DateTime 属性的初始值。</param>
        /// <param name="val">Val 属性的初始值。</param>
        public static 好氧3_DO Create好氧3_DO(global::System.DateTime dateTime, global::System.Double val)
        {
            好氧3_DO 好氧3_DO = new 好氧3_DO();
            好氧3_DO.DateTime = dateTime;
            好氧3_DO.Val = val;
            return 好氧3_DO;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DateTime
        {
            get
            {
                return _DateTime;
            }
            set
            {
                if (_DateTime != value)
                {
                    OnDateTimeChanging(value);
                    ReportPropertyChanging("DateTime");
                    _DateTime = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("DateTime");
                    OnDateTimeChanged();
                }
            }
        }
        private global::System.DateTime _DateTime;
        partial void OnDateTimeChanging(global::System.DateTime value);
        partial void OnDateTimeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double Val
        {
            get
            {
                return _Val;
            }
            set
            {
                OnValChanging(value);
                ReportPropertyChanging("Val");
                _Val = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Val");
                OnValChanged();
            }
        }
        private global::System.Double _Val;
        partial void OnValChanging(global::System.Double value);
        partial void OnValChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Ann
        {
            get
            {
                return _Ann;
            }
            set
            {
                OnAnnChanging(value);
                ReportPropertyChanging("Ann");
                _Ann = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Ann");
                OnAnnChanged();
            }
        }
        private global::System.String _Ann;
        partial void OnAnnChanging(global::System.String value);
        partial void OnAnnChanged();

        #endregion

    
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="QPCHARTModel", Name="好氧4_DO")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class 好氧4_DO : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 好氧4_DO 对象。
        /// </summary>
        /// <param name="dateTime">DateTime 属性的初始值。</param>
        /// <param name="val">Val 属性的初始值。</param>
        public static 好氧4_DO Create好氧4_DO(global::System.DateTime dateTime, global::System.Double val)
        {
            好氧4_DO 好氧4_DO = new 好氧4_DO();
            好氧4_DO.DateTime = dateTime;
            好氧4_DO.Val = val;
            return 好氧4_DO;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DateTime
        {
            get
            {
                return _DateTime;
            }
            set
            {
                if (_DateTime != value)
                {
                    OnDateTimeChanging(value);
                    ReportPropertyChanging("DateTime");
                    _DateTime = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("DateTime");
                    OnDateTimeChanged();
                }
            }
        }
        private global::System.DateTime _DateTime;
        partial void OnDateTimeChanging(global::System.DateTime value);
        partial void OnDateTimeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double Val
        {
            get
            {
                return _Val;
            }
            set
            {
                OnValChanging(value);
                ReportPropertyChanging("Val");
                _Val = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Val");
                OnValChanged();
            }
        }
        private global::System.Double _Val;
        partial void OnValChanging(global::System.Double value);
        partial void OnValChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Ann
        {
            get
            {
                return _Ann;
            }
            set
            {
                OnAnnChanging(value);
                ReportPropertyChanging("Ann");
                _Ann = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Ann");
                OnAnnChanged();
            }
        }
        private global::System.String _Ann;
        partial void OnAnnChanging(global::System.String value);
        partial void OnAnnChanged();

        #endregion

    
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="QPCHARTModel", Name="后缺氧1_MLSS")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class 后缺氧1_MLSS : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 后缺氧1_MLSS 对象。
        /// </summary>
        /// <param name="dateTime">DateTime 属性的初始值。</param>
        /// <param name="val">Val 属性的初始值。</param>
        public static 后缺氧1_MLSS Create后缺氧1_MLSS(global::System.DateTime dateTime, global::System.Double val)
        {
            后缺氧1_MLSS 后缺氧1_MLSS = new 后缺氧1_MLSS();
            后缺氧1_MLSS.DateTime = dateTime;
            后缺氧1_MLSS.Val = val;
            return 后缺氧1_MLSS;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DateTime
        {
            get
            {
                return _DateTime;
            }
            set
            {
                if (_DateTime != value)
                {
                    OnDateTimeChanging(value);
                    ReportPropertyChanging("DateTime");
                    _DateTime = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("DateTime");
                    OnDateTimeChanged();
                }
            }
        }
        private global::System.DateTime _DateTime;
        partial void OnDateTimeChanging(global::System.DateTime value);
        partial void OnDateTimeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double Val
        {
            get
            {
                return _Val;
            }
            set
            {
                OnValChanging(value);
                ReportPropertyChanging("Val");
                _Val = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Val");
                OnValChanged();
            }
        }
        private global::System.Double _Val;
        partial void OnValChanging(global::System.Double value);
        partial void OnValChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Ann
        {
            get
            {
                return _Ann;
            }
            set
            {
                OnAnnChanging(value);
                ReportPropertyChanging("Ann");
                _Ann = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Ann");
                OnAnnChanged();
            }
        }
        private global::System.String _Ann;
        partial void OnAnnChanging(global::System.String value);
        partial void OnAnnChanged();

        #endregion

    
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="QPCHARTModel", Name="后缺氧2_MLSS")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class 后缺氧2_MLSS : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 后缺氧2_MLSS 对象。
        /// </summary>
        /// <param name="dateTime">DateTime 属性的初始值。</param>
        /// <param name="val">Val 属性的初始值。</param>
        public static 后缺氧2_MLSS Create后缺氧2_MLSS(global::System.DateTime dateTime, global::System.Double val)
        {
            后缺氧2_MLSS 后缺氧2_MLSS = new 后缺氧2_MLSS();
            后缺氧2_MLSS.DateTime = dateTime;
            后缺氧2_MLSS.Val = val;
            return 后缺氧2_MLSS;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DateTime
        {
            get
            {
                return _DateTime;
            }
            set
            {
                if (_DateTime != value)
                {
                    OnDateTimeChanging(value);
                    ReportPropertyChanging("DateTime");
                    _DateTime = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("DateTime");
                    OnDateTimeChanged();
                }
            }
        }
        private global::System.DateTime _DateTime;
        partial void OnDateTimeChanging(global::System.DateTime value);
        partial void OnDateTimeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double Val
        {
            get
            {
                return _Val;
            }
            set
            {
                OnValChanging(value);
                ReportPropertyChanging("Val");
                _Val = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Val");
                OnValChanged();
            }
        }
        private global::System.Double _Val;
        partial void OnValChanging(global::System.Double value);
        partial void OnValChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Ann
        {
            get
            {
                return _Ann;
            }
            set
            {
                OnAnnChanging(value);
                ReportPropertyChanging("Ann");
                _Ann = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Ann");
                OnAnnChanged();
            }
        }
        private global::System.String _Ann;
        partial void OnAnnChanging(global::System.String value);
        partial void OnAnnChanged();

        #endregion

    
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="QPCHARTModel", Name="前缺氧1_DO")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class 前缺氧1_DO : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 前缺氧1_DO 对象。
        /// </summary>
        /// <param name="dateTime">DateTime 属性的初始值。</param>
        /// <param name="val">Val 属性的初始值。</param>
        public static 前缺氧1_DO Create前缺氧1_DO(global::System.DateTime dateTime, global::System.Double val)
        {
            前缺氧1_DO 前缺氧1_DO = new 前缺氧1_DO();
            前缺氧1_DO.DateTime = dateTime;
            前缺氧1_DO.Val = val;
            return 前缺氧1_DO;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DateTime
        {
            get
            {
                return _DateTime;
            }
            set
            {
                if (_DateTime != value)
                {
                    OnDateTimeChanging(value);
                    ReportPropertyChanging("DateTime");
                    _DateTime = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("DateTime");
                    OnDateTimeChanged();
                }
            }
        }
        private global::System.DateTime _DateTime;
        partial void OnDateTimeChanging(global::System.DateTime value);
        partial void OnDateTimeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double Val
        {
            get
            {
                return _Val;
            }
            set
            {
                OnValChanging(value);
                ReportPropertyChanging("Val");
                _Val = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Val");
                OnValChanged();
            }
        }
        private global::System.Double _Val;
        partial void OnValChanging(global::System.Double value);
        partial void OnValChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Ann
        {
            get
            {
                return _Ann;
            }
            set
            {
                OnAnnChanging(value);
                ReportPropertyChanging("Ann");
                _Ann = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Ann");
                OnAnnChanged();
            }
        }
        private global::System.String _Ann;
        partial void OnAnnChanging(global::System.String value);
        partial void OnAnnChanged();

        #endregion

    
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="QPCHARTModel", Name="前缺氧2_DO")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class 前缺氧2_DO : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 前缺氧2_DO 对象。
        /// </summary>
        /// <param name="dateTime">DateTime 属性的初始值。</param>
        /// <param name="val">Val 属性的初始值。</param>
        public static 前缺氧2_DO Create前缺氧2_DO(global::System.DateTime dateTime, global::System.Double val)
        {
            前缺氧2_DO 前缺氧2_DO = new 前缺氧2_DO();
            前缺氧2_DO.DateTime = dateTime;
            前缺氧2_DO.Val = val;
            return 前缺氧2_DO;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DateTime
        {
            get
            {
                return _DateTime;
            }
            set
            {
                if (_DateTime != value)
                {
                    OnDateTimeChanging(value);
                    ReportPropertyChanging("DateTime");
                    _DateTime = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("DateTime");
                    OnDateTimeChanged();
                }
            }
        }
        private global::System.DateTime _DateTime;
        partial void OnDateTimeChanging(global::System.DateTime value);
        partial void OnDateTimeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double Val
        {
            get
            {
                return _Val;
            }
            set
            {
                OnValChanging(value);
                ReportPropertyChanging("Val");
                _Val = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Val");
                OnValChanged();
            }
        }
        private global::System.Double _Val;
        partial void OnValChanging(global::System.Double value);
        partial void OnValChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Ann
        {
            get
            {
                return _Ann;
            }
            set
            {
                OnAnnChanging(value);
                ReportPropertyChanging("Ann");
                _Ann = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Ann");
                OnAnnChanged();
            }
        }
        private global::System.String _Ann;
        partial void OnAnnChanging(global::System.String value);
        partial void OnAnnChanged();

        #endregion

    
    }

    #endregion

    
}
